### ISSUE TITLE
How to run this code.?

### ISSUE THREAD

**Issue by DRAhmadFaraz** [s-gupta/rgbd#3]
There is no demo file, and further in runall.m file it needs depth-images and cameraMatrx as an input. what to add in it.?

**Comment by itsagirl** [comment]
How to run this demo, I have the same question, I have loaded all the data and files, but how to run it?Plz
 help.

**Comment by DRAhmadFaraz** [comment]
@itsagirl   Follow this link 

https://github.com/tbhuu/gupta-rgbd

**Comment by itsagirl** [comment]
But I can't find the file named runAll.m? Is it removed by author?

**Comment by itsagirl** [comment]
@DRAhmadFaraz Sir , can you give me the code of runALL.m? Thank you.
