### ISSUE TITLE
Failed, download data.

### ISSUE THREAD

**Issue by leiup** [s-gupta/rgbd#8]
I could's downlaod data from http://www.cs.berkeley.edu/~sgupta/cvpr13/data.tgz.

**Comment by s-gupta** [comment]
Please download from here: https://www.dropbox.com/sh/kbwj2bgu2fd0opv/AADkOjJ6jX75dqgPMKOpAJtVa?dl=0

**Comment by leiup** [comment]
Thx

**Comment by Ahaeflig** [comment]
Hi, could you also provide a link to the precomputed results http://www.cs.berkeley.edu/~sgupta/cvpr13/output.tgz  since the link is also dead?
